version: "3.9"

services:
  rails:
    build: .
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: restaurant-project
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant-project_db
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant-project_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    mem_limit: 1Gb
    image: redis:4-alpine
    command: redis-server --appendonly no
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
